
services:
  web:
    image: php:8.1-fpm
    container_name: pagina
    volumes:
      - ./html:/var/www/html
    ports:
      - "8085:80"
    networks:
      - mynetwork

  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: pagina
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:
